// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGyQDDDN3dt7-jr3gSmCy12Ij24c25_Xs',
    appId: '1:620147953805:web:7e001c3a9822dc5cb752c4',
    messagingSenderId: '620147953805',
    projectId: 'lite-learning-lab',
    authDomain: 'lite-learning-lab.firebaseapp.com',
    databaseURL: 'https://lite-learning-lab.firebaseio.com',
    storageBucket: 'lite-learning-lab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn3rQBPiCd4C7c9AzXCL2YHU7OYFlXvBg',
    appId: '1:620147953805:android:389a231abf4e75ef',
    messagingSenderId: '620147953805',
    projectId: 'lite-learning-lab',
    databaseURL: 'https://lite-learning-lab.firebaseio.com',
    storageBucket: 'lite-learning-lab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjtKr61XQYrCdnRFzXEXtrfjhivAe7AE0',
    appId: '1:620147953805:ios:b5a3cf5b603c5a6db752c4',
    messagingSenderId: '620147953805',
    projectId: 'lite-learning-lab',
    databaseURL: 'https://lite-learning-lab.firebaseio.com',
    storageBucket: 'lite-learning-lab.appspot.com',
    androidClientId: '620147953805-0nnlu46itmhhrg47mamf4dc0gba90avn.apps.googleusercontent.com',
    iosClientId: '620147953805-l67gu10022droknfn8i00drpeo8vnl1t.apps.googleusercontent.com',
    iosBundleId: 'org.mahajob.litelearninglab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjtKr61XQYrCdnRFzXEXtrfjhivAe7AE0',
    appId: '1:620147953805:ios:b5a3cf5b603c5a6db752c4',
    messagingSenderId: '620147953805',
    projectId: 'lite-learning-lab',
    databaseURL: 'https://lite-learning-lab.firebaseio.com',
    storageBucket: 'lite-learning-lab.appspot.com',
    androidClientId: '620147953805-0nnlu46itmhhrg47mamf4dc0gba90avn.apps.googleusercontent.com',
    iosClientId: '620147953805-l67gu10022droknfn8i00drpeo8vnl1t.apps.googleusercontent.com',
    iosBundleId: 'org.mahajob.litelearninglab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ71V7eOu0iAoDj1An7Egv48y1Am9VTD8',
    appId: '1:620147953805:web:0d24dd4ba7b46f66b752c4',
    messagingSenderId: '620147953805',
    projectId: 'lite-learning-lab',
    authDomain: 'lite-learning-lab.firebaseapp.com',
    databaseURL: 'https://lite-learning-lab.firebaseio.com',
    storageBucket: 'lite-learning-lab.appspot.com',
  );
}
